### ISSUE TITLE
Getting this to work

### ISSUE THREAD

**Issue by hvdkooij** [f5devcentral/ansible-role-backup_config#1]
I tried to get this to work with my playbook below

```
---
- name: Fetch a backup from the remote device
  hosts: F5
  roles:
   - { role: f5devcentral.backup_config }
  tasks:
  - name: Backup
    backup_config:
      backup: yes
      path: "~/F5/"
      filename: "config_{{ inventory_hostname }}"
      provider:
        server: "{{ inventory_hostname }}"
        server_port: 443
        user: ansible
        password: ansible
        validate_certs: no
    delegate_to: localhost
```

But it fails with:
**ERROR! couldn't resolve module/action 'backup_config'. This often indicates a misspelling, missing collection, or incorrect module path.**

I installed the module with:
`ansible-galaxy install f5devcentral.backup_config`

So I must be missing out on how to refer to the installed code. And it may be bause I am relative new to ansible and am still trying to get my head around the whole concept. So things I understand but other  just don't connect in my head regardless of how many times I read the ansible documentation.
